```{r}
library(readr)
getwd()

set.seed(1234)

load("work.Rdata")
```

```{r}

getSS <- function(wDF) { 
  # Add the columns of positive weights 
  for(i in 1:length(ctry)) {
    wDF[paste("w0", ctry[i], sep="")] <- 0
  }

  for(t in (winSize+1):nrow(wDF)) { 
    # Add up the positive wegiths 
    sumMax <- 0
    for(i in 1:length(ctry)) {
      if(wDF[t, paste("w", ctry[i], sep="")] > 0) { 
        sumMax <- sumMax + wDF[t, paste("w", ctry[i], sep="")]
      }
    }
    # Plug in adjusted weights when they are positive
    for(i in 1:length(ctry)) {
      if(wDF[t, paste("w", ctry[i], sep="")] > 0) { 
        wDF[t, paste("w0", ctry[i], sep="")] <- wDF[t, paste("w", ctry[i], sep="")] / sumMax
      }
    }
  }
  
  
  # Compute PPP no shortsale returns
  wDF$r0PPP <- wDF$u0 <- 0
  for(t in (winSize+1):nrow(wDF)) { 
  
    #Loop over the countries
    Rpt <- 0
    for ( c in seq(4, (ncol(df)-length(ctry)), (nCat+2) )  ) {
      #print( c(colnames(df)[(c-1)], df[t,c] ) )
      #print( wDF[t, paste("w0",colnames(df)[(c-1)],sep="")] )
      
      if(wDF[t, paste("w0",colnames(df)[(c-1)],sep="")] > 0 ) { 
        #print( c("w", wDF[t, paste("w0",colnames(df)[(c-1)],sep="")] ))
        
        Rpt <- Rpt + as.numeric(wDF[t, paste("w0",colnames(df)[(c-1)],sep="")])*df[t,c]  
      }
    }
  
    wDF$r0PPP[t] <- Rpt
    wDF$u0[t] <- u(Rpt, gamma)
  }
  
  out <- mean(wDF$r0PPP)
  
  return(out)  
}


seqRidge <- c(1, 5, 10, 15, 20)

for(d in seqRidge) { 
  wDF <- as.data.frame(read_csv(file = paste("wDF", d, ".csv", sep="")))
  print(d)
  print(getSS(wDF))
}

ridgeFold <- data.frame(d <- seq(5,30,5), SR <- rep(0,6))
colnames(ridgeFold) <- c("d", "SR")
rownames(ridgeFold) <- ridgeFold$d


# sqVal <- c()
# for(t in (winSize+1):nrow(wDF)) { 
#   sqVal <- c(sqVal, sum(wDF[t,3:54]^2))
# }
# plot(density(sqVal, adjust=0.01))

```

