
```{r}
library(readr)


set.seed(1234)

load("work.Rdata")
```

```{r}
getSS <- function(outInput) {
  
  # Clear the wDF dataframe 
  wDF[,3:ncol(wDF)] <- 0
  
  # Write weights to data frame
  for(i in 1:k) { 
    validate <- flds[paste("Fold", i, sep="")] 
    validate <- unlist(validate, use.names=FALSE)
    
    for(t in validate) { 
      wDF[t,(3:54)] <- outInput[i,]
    }
  }  
  
  

  # Compute PPP weights, returns and utilities
  wDF$rPPP <- wDF$u <- 0
  for(t in 1:nrow(wDF)) { 
    # The vector of countries in period t
    ctryT <- c()
    # Loop over the countries
    for ( c in seq(4, (ncol(df)-length(ctry)), (nCat+2) )  ) {
      # Only for currencies in period t
      if(df[t,c] != 0) { 
        ctryT <- c(ctryT, colnames(df)[(c-1)])  
      }
    }
    
    #Loop over the countries
    Rpt <- 0
    for ( c in seq(4, (ncol(df)-length(ctry)), (nCat+2) )  ) {
      if(colnames(df)[(c-1)] %in% ctryT) { 
        #Get the weight of country c
        wDF[t, paste("w",colnames(df)[(c-1)],sep="")] <- ( 1/length(ctryT) + ( (1/length(ctryT))* (t(as.matrix(as.numeric(wDF[t,3:(nCat+2)]))) %*% as.numeric(df[t,c:(c+nCat-1)]))) )
        
        # Add to the the periot t return with multiplying by period t return
        Rpt <- Rpt + as.numeric(wDF[t, paste("w",colnames(df)[(c-1)],sep="")])*df[t,c]     
      }
    }
    wDF$rPPP[t] <- Rpt
    wDF$u[t] <- u(Rpt, gamma)
  }
  
  # Add the columns of positive weights 
  for(i in 1:length(ctry)) {
    wDF[paste("w0", ctry[i], sep="")] <- 0
  }

  for(t in (winSize+1):nrow(wDF)) { 
    # Add up the positive wegiths 
    sumMax <- 0
    for(i in 1:length(ctry)) {
      if(wDF[t, paste("w", ctry[i], sep="")] > 0) { 
        sumMax <- sumMax + wDF[t, paste("w", ctry[i], sep="")]
      }
    }
    # Plug in adjusted weights when they are positive
    for(i in 1:length(ctry)) {
      if(wDF[t, paste("w", ctry[i], sep="")] > 0) { 
        wDF[t, paste("w0", ctry[i], sep="")] <- wDF[t, paste("w", ctry[i], sep="")] / sumMax
      }
    }
  }
  
  
  # Compute PPP no shortsale returns
  wDF$r0PPP <- wDF$u0 <- 0
  for(t in (winSize+1):nrow(wDF)) { 
  
    #Loop over the countries
    Rpt <- 0
    for ( c in seq(4, (ncol(df)-length(ctry)), (nCat+2) )  ) {
      #print( c(colnames(df)[(c-1)], df[t,c] ) )
      #print( wDF[t, paste("w0",colnames(df)[(c-1)],sep="")] )
      
      if(wDF[t, paste("w0",colnames(df)[(c-1)],sep="")] > 0 ) { 
        #print( c("w", wDF[t, paste("w0",colnames(df)[(c-1)],sep="")] ))
        
        Rpt <- Rpt + as.numeric(wDF[t, paste("w0",colnames(df)[(c-1)],sep="")])*df[t,c]  
      }
    }
  
    wDF$r0PPP[t] <- Rpt
    wDF$u0[t] <- u(Rpt, gamma)
  }
  
  out <- mean(wDF$r0PPP)
  
  return(out)  
}

```




```{r}
getwd()

seqRidge <- c(5, 10, 15, 20)

for(d in seqRidge) { 
  out <- as.data.frame(read_csv(file = paste("out", d, ".csv", sep="")))
  
  print(d)
  print(getSS(out))

}


for(d in seqRidge) { 
  
  
  print(d)
  print(getSS(out))

}




plot(density(as.vector(as.matrix(out)),adjust=0.01))
```



```{r}
out5 <- as.data.frame(read_csv(file = paste("out", 10, ".csv", sep="")))

out5

for(i in 1:8) {
  print(sum(abs(out5[i,])))
  
}

for(i in 1:8) {
  print(sum(out5[i,]^2))
}

as.vector(as.matrix(out5))

plot(density(as.vector(as.matrix(out5)),adjust=0.001))
```

























